In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [12]:
df = pd.read_csv('heart.csv')

In [13]:
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [14]:
df.shape

(303, 14)

In [15]:
x = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [17]:
x_train

     age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
132   42    1   1       120   295  ...      0      0.0      2   0     2
202   58    1   0       150   270  ...      1      0.8      2   0     3
196   46    1   2       150   231  ...      0      3.6      1   0     2
75    55    0   1       135   250  ...      0      1.4      1   0     2
176   60    1   0       117   230  ...      1      1.4      2   2     3
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
188   50    1   2       140   233  ...      0      0.6      1   1     3
71    51    1   2        94   227  ...      1      0.0      2   1     3
106   69    1   3       160   234  ...      0      0.1      1   1     2
270   46    1   0       120   249  ...      0      0.8      2   0     3
102   63    0   1       140   195  ...      0      0.0      2   2     2

[242 rows x 13 columns]

In [18]:
print(x_train.shape)

(242, 13)

In [19]:
print(x_test.shape)

(61, 13)

In [22]:
rf = RandomForestClassifier()
gb = GradientBoostingClassifier()
svc = SVC()
lr = LogisticRegression()

In [23]:
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test, y_pred)

0.8688524590163934

In [24]:
gb.fit(x_train, y_train)
y_pred = gb.predict(x_test)
accuracy_score(y_test, y_pred)

0.7704918032786885

In [25]:
svc.fit(x_train, y_train)
y_pred = svc.predict(x_test)
accuracy_score(y_test, y_pred)

0.7049180327868853

In [26]:
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
accuracy_score(y_test, y_pred)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8852459016393442

In [27]:
rf = RandomForestClassifier(max_samples=0.75, random_state=42)
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test, y_pred)

0.9016393442622951

In [33]:
from sklearn.model_selection import cross_val_score
np.mean(cross_val_score(RandomForestClassifier(max_samples=0.75), x, y, cv=10, scoring="accuracy"))

np.float64(0.831505376344086)

In [36]:
#Number of trees in random forest
n_estimators = [20, 60, 100, 120]

#Number of features to consider at every split
max_features = [0.2, 0.6, 1.0]

#Maximum number of levels in tree
max_depth = [2, 8, None]

# Number of samples
max_samples = [0.5, 0.75, 1.0]

#here multiple combinations of random forest will be trained, according to above criteria 108 combinations will be trained.

In [38]:
param_grid = {
    'n_estimators': n_estimators,
    'max_features': max_features,
    'max_depth': max_depth,
    'max_samples': max_samples,
}
print(param_grid)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0]}

In [40]:
from sklearn.model_selection import GridSearchCV
rf_grid = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, verbose=2, n_jobs=-1)

In [41]:
rf_grid.fit(x_train, y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(max_samples=0.75,
                                              random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 8, None],
                         'max_features': [0.2, 0.6, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [20, 60, 100, 120]},
             verbose=2)

In [42]:
rf_grid.best_params_

{'max_depth': 8, 'max_features': 0.2, 'max_samples': 0.75, 'n_estimators': 20}

In [43]:
rf_grid.best_score_

np.float64(0.8386904761904763)

RandomSearchCV

In [44]:
# Now when dataset is big and hyperparameters are many then grid search cv is slow so use random search cv to tune them.

#Number of trees in random forest
n_estimators = [20, 60, 100, 120]

#Number of features to consider at every split
max_features = [0.2, 0.6, 1.0]

#Maximum number of levels in tree
max_depth = [2, 8, None]

# Number of samples
max_samples = [0.5, 0.75, 1.0]

#Bootstrap samples
bootstrap = [True, False]

#Minimum number of samples required to split a node
min_samples_split = [2, 5]

#Minimum number of samples required at each leaf
min_samples_leaf = [1, 2]

In [45]:
param_grid = {
    'n_estimators': n_estimators,
    'max_features': max_features,
    'max_depth': max_depth,
    'max_samples': max_samples,
    'bootstrap':bootstrap,
    'min_samples_split':min_samples_split,
    'min_samples_leaf':min_samples_leaf,
}
print(param_grid)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0], 'bootstrap': [True, False], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2]}

In [50]:
from sklearn.model_selection import RandomizedSearchCV
rf_random = RandomizedSearchCV(estimator=rf, param_distributions=param_grid, cv=5, verbose=2, n_jobs=-1)
#Randomized search CV randomly picks up some candidates randomly during hyperparameter tuning and leaves others

In [51]:
rf_random.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
40 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_forest.py", line 431, in fit
    raise ValueError(
ValueError: `max_sample` cannot be set if `bootstrap=False`. Either switch to `bootstrap=True` or set `max_sample=None`.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
 0.80170068 0.79761905        nan        nan]
  warnings.warn(

RandomizedSearchCV(cv=5,
                   estimator=RandomForestClassifier(max_samples=0.75,
                                                    random_state=42),
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [2, 8, None],
                                        'max_features': [0.2, 0.6, 1.0],
                                        'max_samples': [0.5, 0.75, 1.0],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 5],
                                        'n_estimators': [20, 60, 100, 120]},
                   verbose=2)

In [52]:
rf_random.best_params_

{'n_estimators': 20,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_samples': 0.5,
 'max_features': 1.0,
 'max_depth': 2,
 'bootstrap': True}

In [53]:
rf_random.best_score_

np.float64(0.8017006802721088)